# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-08 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlingData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(default='', null=True, verbose_name='제목')),
                ('description', models.TextField(default='', null=True, verbose_name='내용')),
                ('response_url', models.TextField(default='', null=True, verbose_name='리스폰링크')),
                ('link', models.TextField(default='', verbose_name='수집링크')),
                ('image_url', models.TextField(default='', null=True, verbose_name='이미지')),
                ('content_id', models.TextField(default='', null=True, verbose_name='HTML')),
                ('content_class', models.TextField(default='', null=True, verbose_name='HTML')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='컨텐츠 등록일')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'get_latest_by': ('created_date',),
                'ordering': ('created_date',),
                'verbose_name_plural': 'Web Crawling Data',
            },
        ),
    ]
